### ISSUE TITLE
hack/update-deps.sh not updating eventing submodule correctly in CI

### ISSUE THREAD

**Issue by creydr** [knative-extensions/eventing-istio#178]
The update-dependencies job does not update the eventing-core submodule correctly while the eventing-kafka-broker submodule is updated correctly.

```
Pulling branch main for submodule /github/workspace/main/third_party/eventing
Already up to date.
```
e.g. in https://github.com/knative-extensions/knobots/actions/runs/7114892104/job/19369892442

This needs to be fixed, so that the dependencies get updated correctly again

Resources:
* Action source: https://github.com/knative-extensions/knobots/blob/main/actions/update-deps/action.yaml
* Workflow runs: https://github.com/knative-extensions/knobots/actions/workflows/auto-update-deps.yaml
* False positive workflow run: https://github.com/knative-extensions/knobots/actions/runs/7114892104/job/19369892442
* update-deps script: https://github.com/knative-extensions/eventing-istio/blob/main/hack/update-deps.sh

**Comment by pierDipi** [comment]
We could try to add more logs as it's currently not clear what is wrong 

- log the submodule remote branch in `update_submodule`
- log current commit sha 
- etc

**Comment by creydr** [comment]
Current log:
The submodules are recognized now correctly after #203.
Anyhow, after hack/update-codegen.sh is run in https://github.com/knative-extensions/knobots/blob/399612e0a785826d9ae4df58edc8e854154a9a8e/actions/update-deps/entrypoint.sh#L65, the changes are not recognized anymore. See https://github.com/knative-extensions/knobots/actions/runs/7256079820/job/19767808948: 
```
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   go.mod
	modified:   go.sum
	modified:   vendor/modules.txt
```

**Comment by creydr** [comment]
unassigned myself if anybody else want to give it a try

**Comment by octonawish-akcodes** [comment]
Can I try?

**Comment by creydr** [comment]
sure

**Comment by creydr** [comment]
Seems we still have the issues after #236: https://github.com/knative-extensions/knobots/actions/runs/7578178889/job/20640351413

**Comment by creydr** [comment]
I think I found the problem:
In the update-deps job, we call `./hack/update-codegen.sh` too (without parameters!):

https://github.com/knative-extensions/knobots/blob/7927c25f2ad10870e2452ce75b312462b66199ab/actions/update-deps/entrypoint.sh#L65

In eventing-istios `./hack/update-codegen.sh`, we call `./hack/update-deps.sh` (without parameters):
https://github.com/knative-extensions/eventing-istio/blob/8588c5a4296ecedab7ce91bcb87995b18bcdfa92/hack/update-codegen.sh#L59

But as we don't pass the parameters (e.g. `--upgrade` or some `--release` info) in the update-deps job and don't pass this in eventing-istios `./hack/update-codegen.sh` to `./hack/update-deps.sh`, we don't update the submodules:
https://github.com/knative-extensions/eventing-istio/blob/8588c5a4296ecedab7ce91bcb87995b18bcdfa92/hack/update-deps.sh#L34-L37


Anyhow not really sure yet, how to solve this, besides updating the update-deps job ([entrypoint.sh](https://github.com/knative-extensions/knobots/blob/7927c25f2ad10870e2452ce75b312462b66199ab/actions/update-deps/entrypoint.sh)) with passing the same arguments to update-codegen.sh and then pass them through update-deps.sh


@pierDipi: FYI ^
